services:
  updater:
    build:
      context: .
      dockerfile: Updater.Dockerfile
    # container_name: dreamy-updater
    volumes:
      - ./:/dreamy-bot
  bot:
    env_file:
      - Bot/.env
    depends_on:
      updater:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Bot.Dockerfile
    # container_name: dreamy-bot
    volumes:
      - ./:/dreamy-bot
      - ./dreamy-data:/dreamy-data